"""Debug CLI for phase 2.

    uv run scripts/chunk.py                      # chunk everything
    uv run scripts/chunk.py --doc trademark      # one document
    uv run scripts/chunk.py --sizes              # chunk-size histogram
    uv run scripts/chunk.py --show "Section 4.3" # print one chunk in full
    uv run scripts/chunk.py --md                 # regenerate docs/chunk-inventory.md

The table is the point: read down the section column and it should look like
the contract's own table of contents. A missing number or a 3000-word chunk
means a heading pattern was missed.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from datetime import date
from statistics import median

from app.chunking import MAX_WORDS, OVERLAP_WORDS, chunk_all, citation_header
from app.config import PROJECT_ROOT, settings

INVENTORY_PATH = PROJECT_ROOT / "docs" / "chunk-inventory.md"


def print_table(chunks: list[dict]) -> None:
    by_doc: dict[str, list[dict]] = defaultdict(list)
    for chunk in chunks:
        by_doc[chunk["doc_id"]].append(chunk)

    for doc_id, doc_chunks in by_doc.items():
        print(f"\n{'=' * 96}\n{doc_chunks[0]['doc_title']}  ({len(doc_chunks)} chunks)\n{'=' * 96}")
        print(f"{'section':<14}{'pages':<9}{'words':>6}  heading")
        print("-" * 96)
        for chunk in doc_chunks:
            pages = (
                f"p.{chunk['page_start']}"
                if chunk["page_start"] == chunk["page_end"]
                else f"pp.{chunk['page_start']}-{chunk['page_end']}"
            )
            parent = f"   (under {chunk['parent_label']})" if chunk["parent_label"] else ""
            print(
                f"{chunk['section_label']:<14}{pages:<9}{chunk['word_count']:>6}  "
                f"{chunk['section_heading'][:48]}{parent}"
            )


def print_sizes(chunks: list[dict]) -> None:
    buckets = Counter()
    for chunk in chunks:
        buckets[min(chunk["word_count"] // 50 * 50, 400)] += 1
    print("\nChunk size distribution (words):")
    for bucket in sorted(buckets):
        label = f"{bucket:>3}-{bucket + 49:<3}" if bucket < 400 else "400+   "
        print(f"  {label} {'#' * buckets[bucket]} {buckets[bucket]}")


def page_range(chunk: dict) -> str:
    if chunk["page_start"] == chunk["page_end"]:
        return f"p.{chunk['page_start']}"
    return f"pp.{chunk['page_start']}-{chunk['page_end']}"


def render_markdown(chunks: list[dict]) -> str:
    """Build the chunk inventory document.

    Generated rather than hand-written, so it cannot quietly disagree with
    what the chunker actually produces.
    """
    by_doc: dict[str, list[dict]] = defaultdict(list)
    for chunk in chunks:
        by_doc[chunk["doc_id"]].append(chunk)

    lines = [
        "# Chunk inventory",
        "",
        f"Generated by `uv run scripts/chunk.py --md` on {date.today().isoformat()}. "
        "Do not edit by hand - regenerate it.",
        "",
        f"Chunks are contract sections, split only when a section exceeds {MAX_WORDS} words "
        f"(with {OVERLAP_WORDS} words of overlap between the pieces). Section labels are what "
        "the answering model is allowed to cite.",
        "",
        "## Summary",
        "",
        "| Document | Pages | Sections | Chunks | Words | Shortest | Median | Longest |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]

    for doc_chunks in by_doc.values():
        counts = [c["word_count"] for c in doc_chunks]
        sections = {c["section_label"] for c in doc_chunks}
        lines.append(
            f"| {doc_chunks[0]['doc_title']} | {max(c['page_end'] for c in doc_chunks)} "
            f"| {len(sections)} | {len(doc_chunks)} | {sum(counts):,} "
            f"| {min(counts)} | {int(median(counts))} | {max(counts)} |"
        )

    totals = [c["word_count"] for c in chunks]
    lines += [
        f"| **All five** | | | **{len(chunks)}** | **{sum(totals):,}** | "
        f"{min(totals)} | {int(median(totals))} | {max(totals)} |",
        "",
        "## Heading style per document",
        "",
        "The same pattern means different things in different contracts, so the style is "
        "detected per document rather than applied globally. A style must fire at least "
        "four times to be believed - that threshold is what stops the transportation "
        "agreement's two stray list items (`1.`, `2.`, inside Article IV) from being read "
        "as its section scheme.",
        "",
        "| Document | Style | Looks like |",
        "| --- | --- | --- |",
        "| Hosting Agreement | inline numbers | `1. Website Design and Development. Client agrees...` |",
        "| Joint Venture Agreement | inline numbers | `3. Capital Contributions. Except as agreed...` |",
        "| Manufacturing Agreement | bare numbers, title on next line | `2.` then `PRODUCTION OF PRODUCT` |",
        "| Trademark License Agreement | `Section N.M` plus coarse parents | `Section 4.3. Termination for Breach.` under `4. Termination.` |",
        "| Transportation Agreement | Roman-numeral Articles | `Article VIII. Fees, Billing & Payment` |",
        "",
        "## Sections",
        "",
    ]

    for doc_chunks in by_doc.values():
        lines += [
            f"### {doc_chunks[0]['doc_title']}",
            "",
            "| Section | Pages | Words | Heading | Parent |",
            "| --- | --- | ---: | --- | --- |",
        ]
        for chunk in doc_chunks:
            heading = chunk["section_heading"].replace("|", "\\|") or "-"
            parent = chunk["parent_label"] or ""
            lines.append(
                f"| {chunk['section_label']} | {page_range(chunk)} | {chunk['word_count']} "
                f"| {heading} | {parent} |"
            )
        lines.append("")

    buckets = Counter(min(c["word_count"] // 50 * 50, 350) for c in chunks)
    lines += ["## Size distribution", "", "| Words | Chunks | |", "| --- | ---: | --- |"]
    for bucket in sorted(buckets):
        label = f"{bucket}-{bucket + 49}" if bucket < 350 else "350+"
        lines.append(f"| {label} | {buckets[bucket]} | {'#' * buckets[bucket]} |")

    lines += [
        "",
        "The twin peaks are expected. Short chunks are genuinely short clauses "
        "(`15. Benefit.` is twenty words). The cluster at 300-350 is long sections that hit "
        f"the {MAX_WORDS}-word ceiling and were split - mostly definitions and production "
        "terms.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Chunk extracted contracts by section.")
    parser.add_argument("--doc", help="only documents whose id contains this text")
    parser.add_argument("--sizes", action="store_true", help="show the size histogram")
    parser.add_argument("--show", metavar="SECTION", help="print chunks with this section label")
    parser.add_argument("--md", action="store_true", help="write docs/chunk-inventory.md")
    args = parser.parse_args()

    chunks = chunk_all(doc_filter=args.doc)
    if not chunks:
        print("No chunks produced. Did you run: uv run scripts/extract.py ?")
        return

    print_table(chunks)
    if args.sizes:
        print_sizes(chunks)

    if args.show:
        matches = [c for c in chunks if c["section_label"].lower() == args.show.lower()]
        for chunk in matches:
            print(f"\n{'=' * 96}\n{citation_header(chunk)}\n{'=' * 96}")
            print(chunk["text"])
        if not matches:
            print(f"\nNo chunk labelled {args.show!r}.")

    if args.md:
        INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
        INVENTORY_PATH.write_text(render_markdown(chunks), encoding="utf-8")
        print(f"\nInventory written to {INVENTORY_PATH}")

    docs = len({c["doc_id"] for c in chunks})
    print(f"\n{len(chunks)} chunks from {docs} documents -> {settings.chunks_dir}")


if __name__ == "__main__":
    main()
